# CCT College Dublin

# Assessment Cover Page

---

**Module Title:**  
Data Visualisation and Communication

**Assessment:**  
CA.1

**Lecturer Name:**  
Taufique Ahmed

**Student Name:**  
Subhan Arshad

**Student Number:**  
2023307

**Assessment Due Date:**  
04 October 2026

**Date of Submission:**  
7 November 2026 @ 23:59

**GitHub Repository Link:**  
https://github.com/Subhanarshad4455/CA.1-40-AI-Employment-Visualisation

**Video Link:**  
To be added after recording the 4-minute presentation.

---

## Declaration

By submitting this assessment, I confirm that I have read the CCT policy on Academic Misconduct and understand the implications of submitting work that is not my own or does not appropriately reference material taken from a third party or other source. I declare it to be my own work and that all material from third parties has been appropriately referenced. I further confirm that this work has not previously been submitted for assessment by myself or someone else in CCT College Dublin or any other higher education institution.

# AI, Data Science & Software Development Employment Analysis
## 1. Introduction

In order to investigate employment in fields linked to software development, data science, and artificial intelligence (AI), this study examines employment data from the United States. The U.S. Bureau of Labor Statistics (BLS) Occupational Employment and Wage Statistics (OEWS) employment data for May 2023 is used in the research.

The goal of this project is to compare employment across relevant occupations, find trends, and learn more about employment in technology-related industries using data visualization tools.

## 2. Dataset

The Occupational Employment and Wage Statistics (OEWS) dataset for May 2023 from the U.S. Bureau of Labor Statistics (BLS) is the source of employment data used in this research. Employment estimates for a variety of professions in the US are provided by the dataset. It contains data like total employment, profession codes, and occupation titles. Each occupation is identified by the `OCC_CODE` and `OCC_TITLE` columns, and the estimated number of workers in each occupation is displayed by the `TOT_EMP` column. This dataset will be used to investigate and contrast employment in software development, data science, and artificial intelligence-related fields.

In [9]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
file_path = r"D:\4th Year\all_data_M_2023.xlsx"
df = pd.read_excel(file_path)
df.head()

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,00-0000,All Occupations,...,23.11,37.01,58.4,29050,35660,48060,76980,121470,NaN,NaN
1,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,56.19,81.29,111.36,54550,78330,116880,169090,231620,NaN,NaN
2,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1000,Top Executives,...,49.74,79.57,#,46400,66170,103460,165500,#,NaN,NaN
3,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1010,Chief Executives,...,99.37,#,#,80000,130840,206680,#,#,NaN,NaN
4,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1011,Chief Executives,...,99.37,#,#,80000,130840,206680,#,#,NaN,NaN

In [7]:
print("Dataset shape:", df.shape)

Dataset shape: (413327, 32)

In [8]:
df.columns

Index(['AREA', 'AREA_TITLE', 'AREA_TYPE', 'PRIM_STATE', 'NAICS', 'NAICS_TITLE',
       'I_GROUP', 'OWN_CODE', 'OCC_CODE', 'OCC_TITLE', 'O_GROUP', 'TOT_EMP',
       'EMP_PRSE', 'JOBS_1000', 'LOC_QUOTIENT', 'PCT_TOTAL', 'PCT_RPT',
       'H_MEAN', 'A_MEAN', 'MEAN_PRSE', 'H_PCT10', 'H_PCT25', 'H_MEDIAN',
       'H_PCT75', 'H_PCT90', 'A_PCT10', 'A_PCT25', 'A_MEDIAN', 'A_PCT75',
       'A_PCT90', 'ANNUAL', 'HOURLY'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413327 entries, 0 to 413326
Data columns (total 32 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   AREA          413327 non-null  int64
 1   AREA_TITLE    413327 non-null  object
 2   AREA_TYPE     413327 non-null  int64
 3   PRIM_STATE    413327 non-null  object
 4   NAICS         413327 non-null  object
 5   NAICS_TITLE   413327 non-null  object
 6   I_GROUP       413327 non-null  object
 7   OWN_CODE      413327 non-null  int64
 8   OCC_CODE      413327 non-null  object
 9   OCC_TITLE     413327 non-null  object
 10  O_GROUP       413327 non-null  object
 11  TOT_EMP       413327 non-null  object
 12  EMP_PRSE      413327 non-null  object
 13  JOBS_1000     235826 non-null  object
 14  LOC_QUOTIENT  235826 non-null  object
 15  PCT_TOTAL     170470 non-null  object
 16  PCT_RPT       170470 non-null  object
 17  H_MEAN        413327 non-null  object
 18  A_MEAN        413327 non-null  object
 19  MEAN_PRSE     413327 non-null  object
 20  H_PCT10       413327 non-null  object
 21  H_PCT25       413327 non-null  object
 22  H_MEDIAN      413327 non-null  object
 23  H_PCT75       413327 non-null  object
 24  H_PCT90       413327 non-null  object
 25  A_PCT10       413327 non-null  object
 26  A_PCT25       413327 non-null  object
 27  A_MEDIAN      413327 non-null  object
 28  A_PCT75       413327 non-null  object
 29  A_PCT90       413327 non-null  object
 30  ANNUAL        16497 non-null   object
 31  HOURLY        755 non-null     object
dtypes: int64(3), object(29)
memory usage: 100.9+ MB

In [11]:
df.isnull().sum()

AREA                 0
AREA_TITLE           0
AREA_TYPE            0
PRIM_STATE           0
NAICS                0
NAICS_TITLE          0
I_GROUP              0
OWN_CODE             0
OCC_CODE             0
OCC_TITLE            0
O_GROUP              0
TOT_EMP              0
EMP_PRSE             0
JOBS_1000       177501
LOC_QUOTIENT    177501
PCT_TOTAL       242857
PCT_RPT         242857
H_MEAN               0
A_MEAN               0
MEAN_PRSE            0
H_PCT10              0
H_PCT25              0
H_MEDIAN             0
H_PCT75              0
H_PCT90              0
A_PCT10              0
A_PCT25              0
A_MEDIAN             0
A_PCT75              0
A_PCT90              0
ANNUAL          396830
HOURLY          412572
dtype: int64

In [12]:
df["OCC_TITLE"].head(20)

0                                       All Occupations
1                                Management Occupations
2                                        Top Executives
3                                      Chief Executives
4                                      Chief Executives
5                       General and Operations Managers
6                       General and Operations Managers
7                                           Legislators
8                                           Legislators
9     Advertising, Marketing, Promotions, Public Rel...
10                  Advertising and Promotions Managers
11                  Advertising and Promotions Managers
12                         Marketing and Sales Managers
13                                   Marketing Managers
14                                       Sales Managers
15            Public Relations and Fundraising Managers
16                            Public Relations Managers
17                                 Fundraising Managers
18                      Operations Specialties Managers
19      Administrative Services and Facilities Managers
Name: OCC_TITLE, dtype: object

In [13]:
df[df["OCC_TITLE"].str.contains(
    "data scientist|software developer|computer scientist|machine learning|artificial intelligence",
    case=False,
    na=False
)][["OCC_CODE", "OCC_TITLE", "TOT_EMP"]].head(30)

     OCC_CODE            OCC_TITLE  TOT_EMP
149   15-1252  Software Developers  1656880
164   15-2050      Data Scientists   192710
165   15-2051      Data Scientists   192710
1547  15-1252  Software Developers  1628050
1562  15-2050      Data Scientists   184720
1563  15-2051      Data Scientists   184720
2856  15-1252  Software Developers       50
3215  15-1252  Software Developers      800
3222  15-2050      Data Scientists      360
3223  15-2051      Data Scientists      360
3741  15-1252  Software Developers     2360
3750  15-2050      Data Scientists      810
3751  15-2051      Data Scientists      810
4269  15-1252  Software Developers     2800
4278  15-2050      Data Scientists      440
4279  15-2051      Data Scientists      440
5019  15-1252  Software Developers    60190
5030  15-2050      Data Scientists     6790
5031  15-2051      Data Scientists     6790
5985  15-1252  Software Developers   339170
6000  15-2050      Data Scientists    22240
6001  15-2051      Data Scientists    22240
6661  15-1252  Software Developers   147320
6674  15-2050      Data Scientists    33620
6675  15-2051      Data Scientists    33620
7236  15-1252  Software Developers     4420
7243  15-2050      Data Scientists     1230
7244  15-2051      Data Scientists     1230
7922  15-1252  Software Developers   718500
7937  15-2050      Data Scientists    60800